trying to understand exceptions in production regarding updating a social user info
java.lang.Exception: Error updating SocialUserInfo: Some(95891), Kafee Saann
com.keepit.common.social.SocialGraphActor[a].apply(SocialGraphPluginImpl.scala:126)
com.keepit.common.social.SocialGraphActor[a].apply(SocialGraphPluginImpl.scala:85)
com.keepit.common.performance.package$.timing(package.scala:41)
com.keepit.common.social.SocialGraphActor.fetchUserInfo(SocialGraphPluginImpl.scala:84)
com.keepit.common.social.SocialGraphActor[a].applyOrElse(SocialGraphPluginImpl.scala:78)
akka.actor.Actor$class.aroundReceive(Actor.scala:465)
com.keepit.common.akka.FortyTwoActor.aroundReceive(FortyTwoActor.scala:22)
akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
akka.actor.ActorCell.invoke(ActorCell.scala:487)
akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
akka.dispatch.Mailbox.run(Mailbox.scala:220)
akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Cause:
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: error persisting SocialUserInfo[Id=Some(95891),User=Some(249),Name=Kafee Saann,network=facebook,socialId=100005988399160]
com.keepit.common.db.slick.DbRepo$class.save(DbRepo.scala:84)
com.keepit.model.SocialUserInfoRepoImpl.save(SocialUserInfoRepo.scala:71)